"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect,useRef } from "react";
import type { Product } from "@/types/product";
import { InventoryStatus } from "./InventoryStatus";
import { ProductStatusBadge } from "./ProductStatusBadge";
const currency=new Intl.NumberFormat("en-IE",{style:"currency",currency:"EUR"});
function SelectAllCheckbox({checked,indeterminate,onChange}:{checked:boolean;indeterminate:boolean;onChange:()=>void}){const ref=useRef<HTMLInputElement>(null);useEffect(()=>{if(ref.current)ref.current.indeterminate=indeterminate},[indeterminate]);return <input ref={ref} type="checkbox" aria-label="Select all visible products" checked={checked} onChange={onChange} className="size-4 cursor-pointer accent-[#303030]"/>}
export function ProductsTable({products,selected,onSelect,onSelectAll}:{products:Product[];selected:Set<number>;onSelect:(id:number)=>void;onSelectAll:()=>void}){const selectedVisible=products.filter((product)=>selected.has(product.id)).length;return <div className="overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-left text-[13px]"><caption className="sr-only">Store products</caption><thead className="border-b bg-[var(--color-surface-subdued)] text-[12px] text-[var(--color-text-secondary)]"><tr><th className="w-11 px-4 py-2"><SelectAllCheckbox checked={selectedVisible===products.length&&products.length>0} indeterminate={selectedVisible>0&&selectedVisible<products.length} onChange={onSelectAll}/></th><th className="px-2 py-2 font-medium">Product</th><th className="px-3 py-2 font-medium">Status</th><th className="px-3 py-2 font-medium">Inventory</th><th className="px-3 py-2 font-medium">Category</th><th className="px-3 py-2 text-right font-medium">Price</th><th className="px-4 py-2 text-right font-medium">Sales</th></tr></thead><tbody className="divide-y">{products.map((product)=><tr key={product.id} className={`group transition-colors hover:bg-[var(--color-surface-subdued)] ${selected.has(product.id)?"bg-[#f1f5f3]":"bg-[var(--color-surface)]"}`}><td className="px-4 py-2.5"><input type="checkbox" aria-label={`Select ${product.name}`} checked={selected.has(product.id)} onChange={()=>onSelect(product.id)} className="size-4 cursor-pointer accent-[#303030]"/></td><td className="px-2 py-2.5"><Link href={`/products/${product.id}`} className="flex items-center gap-3"><Image src={product.image.src} alt={product.image.alt} width={40} height={40} className="size-10 shrink-0 rounded-[var(--radius-sm)] border object-cover"/><span className="min-w-0"><span className="block truncate font-semibold text-[var(--color-text)] underline-offset-2 group-hover:underline">{product.name}</span><span className="block text-[11px] text-[var(--color-text-muted)]">SKU: {product.sku}</span></span></Link></td><td className="px-3 py-2.5"><ProductStatusBadge status={product.status}/></td><td className="px-3 py-2.5"><InventoryStatus product={product}/></td><td className="px-3 py-2.5 text-[var(--color-text-secondary)]">{product.category.name}</td><td className="whitespace-nowrap px-3 py-2.5 text-right font-semibold tabular-nums">{currency.format(Number(product.price))}</td><td className="whitespace-nowrap px-4 py-2.5 text-right text-[var(--color-text-secondary)]">{product.totalSales} sold</td></tr>)}</tbody></table></div>}
